# conda version 24.7.1
# mamba version 1.5.8
# miniforge

## somehow this does not work with stardist.....
name: stardist0
channels:
#  - defaults
  - conda-forge
  - nodefaults #this is a channel that enforces avoidance of the defaults channel
  - pytorch
  - nvidia
dependencies:
  - python
  - pip

  - bioconda::snakemake
  - ipython
  - scikit-image
  - stardist
  - tensorflow

  - pip:


