# conda version 24.3.0
# mamba version 1.5.8
name: morphody30
channels:
#  - defaults
  - conda-forge
dependencies:
  - python
  - pip

  - aicsimageio
  - anndata
  - bioconda::snakemake
  - btrack
  - czifile
  - colour
  - hdbscan
  - imbalanced-learn
  - ipywidgets
  - jpype1
  - jupyterlab
  - jupytext
  - matplotlib
  - micro_sam
  - napari=0.4.18 #this has to be this version otherwise on newer versions you get segfaults on labels
  - napari-aicsimageio
  - notebook
  - numba
  - numpy
  - opencv
  - openpyxl
  - pandas
  - pillow
  - pims
  - python-elf
  - pyqt
  - pytables
  - readlif
  - requests
  - scanpy
  - scikit-image
  - scikit-learn
  - stardist
  - tensorflow
  - torch_em
  - tqdm
  - umap-learn
  - xlrd
  - xlwt
  - xmlschema
  - xmltodict

#lxml
# - urllib3=2.0.7 #this is the version that morphodynamics tries to install, replacing another one if not specified
  - pip:
#    - tensorflow[and-cuda]
#    - morphodynamics
#    - git+https://github.com/guiwitz/napari-morphodynamics.git
#    - cellpose[gui] #We recommend python 3.8, but python 3.9 and 3.10 will likely work as well
    - aicspylibczi
#    - czitools #this package changes a lot of tools from the conda environment, so 
#       if I need it I will have to solve for this later or put it in a different environment
