#trying to include micro sam in this environment
# conda version 24.3.0
# mamba version 1.5.8
# miniforge
name: morphody12
channels:
#  - defaults
  - conda-forge
#  - pytorch
#  - nvidia
dependencies:
  - python
  - pip

  - aicsimageio
  - anndata
  - bioconda::snakemake
  - btrack
  - colour
  - hdbscan
  - imbalanced-learn
  - ipywidgets
  - jpype1
  - jupyterlab
  - jupytext
  - matplotlib
  - micro_sam
  - napari
  - napari-aicsimageio #removing this doesn't solve the problem
  - notebook
  - numba
  - numpy
#  - opencv
  - openpyxl
  - pandas
#  - pillow
  - pims
  - pyqt
  - pytables
  - python-elf #this is part of micro_sam
  - readlif
  - requests
  - scanpy
  - scikit-image
  - scikit-learn
  - stardist
  - tensorflow
  - torch_em #this is part of micro_sam
  - tqdm
  - umap-learn
  - xlrd
  - xlwt
  - xmlschema
  - xmltodict

#lxml
# - urllib3=2.0.7 #this is the version that morphodynamics tries to install, replacing another one if not specified
  - pip:
#    - tensorflow[and-cuda]
#    - morphodynamics
#    - git+https://github.com/guiwitz/napari-morphodynamics.git
#    - cellpose[gui] #We recommend python 3.8, but python 3.9 and 3.10 will likely work as well
#    - aicspylibczi
